//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Shared;

    public partial class autenticacionEntities : DbContext
    {
        public autenticacionEntities()
            : base("name=autenticacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Shared.Entidades.Admins> Admins { get; set; }
        public virtual DbSet<Shared.Entidades.Ciudades> Ciudades { get; set; }
    }
}
